### ISSUE TITLE
I can build a server side code

### ISSUE THREAD

**Issue by webiummedia** [Odrin/Droid-Watcher#10]
Hi Odrin, I would be very happy to pitch in and create a server side script that would work. Can you join me on skype? web2c.psimard

If your intrested in reviving this project and make it work for android 7.0 at least you wont be alone this time hehe I guess the best thing would be to make it work with Firebase cloud massaging this time. Whats your thoughts?

**Comment by webiummedia** [comment]
Started working on something

![image](https://cloud.githubusercontent.com/assets/4869819/21281282/71632e88-c3b9-11e6-9eef-400668c7c865.png)

**Comment by exrienz** [comment]
@Patrick, seem cool.. I also want to join the project but im not sure how
can i contribute to the project. Im not used with firebase. 😂..currently
Im building the client side apps for android.. N so far working until api
5.1.1..my code also not as cool as Odrin as i still newbie 😂.. However,
ill try my best to contribute 😀.

Some device like xiomi n oppo had a stric restriction especially for
background service.. It keep kill my background service. 😠

**Comment by webiummedia** [comment]
Hi @exrienz , My programmer and I are also working on this. Perhaps we should help each other out. Can you contact me on skype? Tell me your exrienz and i will accept you request

**Comment by exrienz** [comment]
Definitely, will do. Thanks 😊

**Comment by webiummedia** [comment]
@exrienz did you send me your skype invite?

**Comment by jifilis** [comment]
A fork with your changes? Android 7 compatible?
:)

**Comment by exrienz** [comment]
Yep... I already send the skype invitation 😊

**Comment by RogerMonteiro124** [comment]
@webiummedia  Can you share this source code on the server side? my email is rogermonteiro15@outlook.com

**Comment by serj2k** [comment]
Please, send me too. my email is serj2k@gmail.com

2017-01-12 20:53 GMT+03:00 RogerMonteiro124 <notifications@github.com>:

**Comment by ZeeshanShabbir** [comment]
@webiummedia  how did you convert the project into the android studio?? I get this build error? Can you help me out? 
`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs`

**Comment by ricardo** [comment]
@webiummedia , I'd also like to contribute. I'll reach to you on Skype

**Comment by levibarasa** [comment]
@webiummedia , I'd also like to contribute. I'll reach to you on Skype

**Comment by raiaslam** [comment]
I also need the source code on the server side, please share with me .any one please help me...
asalmbscs@gmail.com

**Comment by vivek98799** [comment]
I also need the source code on the server side, please share with me .any one please help me...
realbund@gmail.com

**Comment by elfelround** [comment]
i want to contribute 2, mr.programs@yandex.com

**Comment by syafiqsaidi** [comment]
May i have the server side files for testing?

**Comment by syafiqsaidi** [comment]
Benjamin_syafiq@yahoo.com

**Comment by boygaggoo** [comment]
ziadevtmc@gmail.com 
anyone can please forward me server side code with db and client side. I really appreciate.

**Comment by Junaid1111** [comment]
I have resolved this project issues on android studio and its working fine on android 6.0,
Kindly Send me Server code here,
jdrana11@gmail.com

Thanks in advance,

**Comment by Cool500** [comment]
Everyone asking for server side script. Does anyone find the solution of it?

**Comment by ricardo** [comment]
@Junaid1111 , Can you send me the client side code? So I could try and do something about the server side code and share with you.

**Comment by Junaid1111** [comment]
Sure @ricardo ,
Send me your Email id

**Comment by Junaid1111** [comment]
@Cool500  I think @webiummedia seems like working on some thing,
@webiummedia ,A little Bit Help here

**Comment by ricardo** [comment]
@Junaid1111 my email is ricardometring@gmail.com

**Comment by ZeeshanShabbir** [comment]
@Junaid1111  i need android working project. Can you please share the source code with me?

**Comment by vivek98799** [comment]
I am just near the project any client side code would be appreciable my
email id v123r123@gmail.com   to full-fill my puzzlee..

**Comment by Junaid1111** [comment]
@vivek98799 ,do you have server side??

**Comment by ZeeshanShabbir** [comment]
@Junaid1111  zeeshan.shabbir79@gmail.com is my email. Please share client side code with me. Thanks

**Comment by Junaid1111** [comment]
Here is the link of working Client side,
https://www.dropbox.com/s/tt5t2j0l9u5lf9y/DroidWatcher.rar?dl=0

**Comment by Junaid1111** [comment]
I have share link on GitHub comments,

**Comment by Sreekanth-Unnikrishnan** [comment]
Guys anyone have the server side source code ? 
Please share with me.  
E-mail : smussr.dev@gmail.com

**Comment by vivek98799** [comment]
@Junaid1111 <https://github.com/junaid1111>  please help me with some
scratch code personally, refer trail mail to find my email id, TQ :)

**Comment by Junaid1111** [comment]
@vivek98799 ,contact me 
jdrana11@gmail.com

**Comment by cool125** [comment]
@Junaid1111 i think @webiummedia is sleeping since its last post.  may be he did prank with us to share fake image of server side view.

**Comment by cool125** [comment]
i have initial server side script which required modification , only an expert can do this.  if any expert here then contact me on Telegram. my id is   rbc11

**Comment by vivek98799** [comment]
is anyone interest to doing business profit with me by launching android
spy application ????? just let me know privately..
