### ISSUE TITLE
SERVER

### ISSUE THREAD

**Issue by kartx22** [Odrin/Droid-Watcher#6]
Hi first of all huge appreciate for this project. I'm interested in working on server side, Can you provide me the source code? E-mail: kartx.rockeveryone@gmail.com thankyou.

**Comment by roger-sd** [comment]
Hi @kartx22 , if the @Odrin  send you the code you can give me also my email : [roger-15monteiro@hotmail.com](url)

**Comment by tuivilla7770** [comment]
Hi @Ordin, I am really interested in your project, can you please provide me the source code of server side... Please ... tuivilla7770@gmail.com thank you

**Comment by roger-sd** [comment]
Hi @tuivilla7770 ,
If you get the code you can send on my email [roger-15monteiro@hotmail.com](url)

**Comment by roger-sd** [comment]
Recebi seu email @tuivilla7770 , não pude responder mas estarei respondendo o mais breve possível.
Se o Odrin me enviar o código fonte do lado do servidor web, certamente vou te enviar.

**Comment by Odrin** [comment]
#5
