### ISSUE TITLE
source code server side .

### ISSUE THREAD

**Issue by roger-sd** [Odrin/Droid-Watcher#7]
Hi @Odrin , 
you can pass me the source code side web server to my email : [roger-15monteiro@hotmail.com](url)

**Comment by Odrin** [comment]
#5

**Comment by levibarasa** [comment]
Hi @Odrin ,
you can pass me the source code side web server to my email lvbarasa@gmail.com

**Comment by Raiikram** [comment]
if any one have server side code please send me on raiik44@gmail.com
