### ISSUE TITLE
Hi Odrin

### ISSUE THREAD

**Issue by exrienz** [Odrin/Droid-Watcher#8]
I manage to set it working on android studio. However i had no clue on how the server side works. Can you please send me the source code of its server side. I need it for my thesis. Pleaseee. I dont mind if its not complete etc, i just need a rough idea on how it grab the data n process it.. Pleaseee..... 😅😅

If you do, please email me at exrienz@gmail.com. Your help is much appreciated. Thanks for sharing this great code.

**Comment by RogerMonteiro124** [comment]
I also need the source code on the server side, please share with us Odrin.

**Comment by logitek45** [comment]
Hi, I will be really gratefull if you share this code with me too. 

logitek45@gmail.com

**Comment by lordcharlx** [comment]
hi team ...I also want a look at the source ....charlx@mail.ru

**Comment by levibarasa** [comment]
hi team ...I also want a look at the source ....lvbarasa@gmail.com

**Comment by raiaslam** [comment]
I also need the source code on the server side, please share with me .any one please help me...
aslambscs@gmail.com

**Comment by vivek98799** [comment]
I also need the source code on the server side, please share with me .any one please help me...
aslambscs@gmail.com

**Comment by venki0552** [comment]
I also need the source code on the server side, please share with me .any one please help me...
venkatareddya91@gmail.com

**Comment by vivek98799** [comment]
m e too

**Comment by Mode-XDigitalDevelopment** [comment]
Has anyone had a reply yet regarding the server side code? Ive setup a simple php file on the server that the app points to but the app just gets a 404 error. I have disabled login etc so it should be getting the POST but doesn't seem to work..... Odrin are you able to provide the server side script/code that u you used for the data upload ?

**Comment by exrienz** [comment]
This project is already closed guys. Odrin no longer support this project

**Comment by vivek98799** [comment]
hey plz any one have copy of the same please share it.
